<?php
/**
 * @author Excellencestar
 * @copyright Copyright (c) 2020 Excellencestar
 * @package Excellencestar_InvisibleCaptcha
 */
?>
<?php
/**
 * Captcha block template
 *
 * @var \Excellencestar\InvisibleCaptcha\Block\Captcha $block
 */
$config = $block->getConfig();
?>
<script type="text/javascript">
    require(['jquery'], function ($) {
    	var recaptcha = [],
            formsToProtect = '<?= $block->escapeJs(implode(',', $config->getAllFormSelectors())) ?>';
        window.formToProtectOnPage = [];
        $.each($(formsToProtect), function (index, formToProtect) {
            window.formToProtectOnPage.push(formToProtect);
        });
        
        if (window.formToProtectOnPage.length) {
            var recaptchaScript = document.createElement('script');
            recaptchaScript.src = 'https://www.google.com/recaptcha/api.js?onload=InvisibleCaptchaOnloadCallback&render=explicit<?= $block->escapeHtml($config->getLanguage()); ?>';
            recaptchaScript.attributes = 'async defer';
            document.body.appendChild(recaptchaScript);
        }

        window.InvisibleCaptchaOnloadCallback = function () {
            for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                var tokenInput = document.createElement('input');
                tokenInput.type = 'hidden';
                tokenInput.name = 'captcha_invisible_token';
                window.formToProtectOnPage[i].appendChild(tokenInput);
            }
            var renderCaptcha = function(event, form, id) {
                recaptcha[i] = grecaptcha.render(id, {
                    'theme': '<?= $block->escapeHtml($config->getBadgeTheme()); ?>',
                    'badge': '<?= $block->escapeHtml($config->getBadgePosition()); ?>',
                    'sitekey': '<?= $block->escapeHtml($config->getSiteKey()); ?>',
                    'callback': function(token) {
                        if ($(form).valid()) {
                            form.querySelector("[name='captcha_invisible_token']").setAttribute('value', token);
                            $(form).submit();
                        }
                        for (var j = 0; j < recaptcha.length; j++) {
                            grecaptcha.reset(recaptcha[j]);
                        }
                    }
                });
            };
            for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                var form = window.formToProtectOnPage[i];
                if (form.tagName.toLowerCase() != 'form') {
                    continue;
                }
                var id = form.querySelector("[type='submit']");
                renderCaptcha(null, form, id);
            }
        };
    });
</script>
